---
title: "resume"
format:
  html:
    theme: cosmo
    fontsize: 1.2rem
    mainfont: Georgia, serif
    fontcolor: rebeccapurple
    linkcolor: "#00a400"
    
---
Yufei Wang
Contact Information
Email: ywang654@uic.edu
Education
MSCA
University of illinois Chicago
GPA: 3.5/4.0
Work Experience
Teaching Assistant at New Oriental Company (2019 - 2023)
Assisted in preparing and delivering engaging lesson plans for various subjects, ensuring a stimulating learning environment for students.
Provided individualized support to students, addressing their specific needs and helping them achieve their academic goals.
Collaborated with lead teachers to evaluate students’ progress and implement effective teaching strategies.
Utilized multimedia tools and educational software to enhance the learning experience and keep students engaged.
Organized and participated in extracurricular activities, fostering a sense of community and promoting students’ holistic development.
Maintained open communication with parents and guardians, providing regular updates on students’ progress and addressing any concerns.
Skills
Programming Languages: C,C++
Tools: Rstudio,Visual Studio